### ISSUE TITLE
I got this issue 

### ISSUE THREAD

**Issue by NoobOnCoffee** [co60ca/EmotionNet2#10]
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'emotionnet'
```
HELP!!!

**Comment by co60ca** [comment]
@NoobOnCoffee I didn't respond to this because I was on vacation, but if you are running into this error it seems you don't have a strong familiarity with how the Python interpreter finds modules.

> Start python3 from the root directory with the PYTHONPATH=python as the python scripts are in the python directory.

You likely missed the above step and accomplishing this step is something that as a python user you should understand before trying to use complicated libraries.

I'm closing as not a problem with my software.
