### ISSUE TITLE
Is there any accuracy improvement from original project?

### ISSUE THREAD

**Issue by KamalAwasthi** [co60ca/EmotionNet2#4]
Is there any accuracy improvement too or this is just a version upgrade and addition of face detection feature?

**Comment by co60ca** [comment]
It should generalize better. Before we had issues with density. I haven't fully tested the generalization but it seemed to be better performing. The training/validation accuracy seemed to be lower but we think in the original EmotionNet that the metrics we used (due to how we trained it) were skewed.

Closing but feel free to reply more if you'd like.
