### ISSUE TITLE
Problem with the pretrained model 

### ISSUE THREAD

**Issue by ludoga** [co60ca/EmotionNet2#9]
Hi,

I have tried to test your pretrained model but the result are really weird.

On a photo from KDEF of a women smiling, I get this ouput
<img width="752" alt="output" src="https://user-images.githubusercontent.com/39762487/40891674-6bac7cb2-678a-11e8-90be-6580cd14a53f.png">
Could you give me some more infos?

Thanks

**Comment by co60ca** [comment]
So that is the averaged KDEF picture. The pretrained network is only trained on the KDEF dataset so the network only understands the distribution of human faces using that dataset anything unlike those photos may not classify as well.

If we wanted to improve performance on more pictures we would need more labeled examples.

KDEF images from the dataset look like this one below.

![am12afs](https://user-images.githubusercontent.com/6857411/40892569-f2b045be-6766-11e8-93cb-b08338a46ee4.JPG)

This type of image (one directly from KDEF) should classify well, in fact perfectly, in most cases. This is because we trained on these images but not on the averaged image you've shown above.

I'll close this but feel free to comment if you feel necessary.
